# Generated by Django 4.1.7 on 2023-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
