# Generated by Django 5.0 on 2023-12-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_crud_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crud',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
